version: v2beta1
name: bills

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: |-
      start_dev app                # Start dev mode "app" (see "dev" section)

# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
  app:
    # Search for the container that runs this image
    labelSelector:
      app: bills-be
    container: bills-be-fpm
    # Replace the container image with this dev-optimized image (allows to skip image building during development)
    devImage: ghcr.io/yarsoniy/bills-be-fpm:dev-main
    # Sync files between the local filesystem and the development container
    env:
      - name: APP_ENV
        value: dev
      - name: APP_DEBUG
        value: "1"
      - name: PHP_IDE_CONFIG
        value: "serverName=bills-be-fpm"

    reversePorts:
      - port: "9003:9003"   # host-port:container-port
    sync:
      - path: ./
        excludePaths:
          - /.git/
          - /.idea/
          - /var/log/
          - /var/cache/
          - /vendor/
          - /tools/php-cs-fixer/vendor/
      - path: ./var/cache/
        initialSync: mirrorRemote
        disableUpload: true
      - path: ./vendor/
        initialSync: mirrorRemote
        disableUpload: true
      - path: ./tools/php-cs-fixer/vendor/
        initialSync: mirrorRemote
        disableUpload: true

