version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/build/dev/Dockerfile
      target: nginx
    ports:
      - "80:80"
    networks:
      - default
    environment:
      TZ: 'Europe/Kiev'
    volumes:
      - .:/code:delegated
    restart: always
  php:
    build:
      context: "."
      dockerfile: ./docker/build/dev/Dockerfile
      target: fpm
    environment:
      TZ: 'Europe/Kiev'
      XDEBUG_CONFIG: client_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=bills
    volumes:
      - .:/code:delegated
    restart: always

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
