version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/build/Dockerfile
      target: nginx
    ports:
      - "3001:80"
    networks:
      - default
    restart: always
  php:
    build:
      context: "."
      dockerfile: docker/build/Dockerfile
      target: fpm-prod
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
    restart: always

