kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-{{.Values.appName}}-fpm
  namespace: {{.Release.Namespace}}
data:
  TZ: 'Europe/Kiev'
  APP_ENV: "prod"
  APP_DEBUG: "0"
  MONGO_CONNECTION_URL: "mongodb://root:example@svc-bills-mongo"
