apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.appName}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: configmap-{{.Values.appName}}-nginx-config
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: {{.Values.appName}}-fpm
          image: ghcr.io/yarsoniy/bills-be-fpm:main
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: configmap-{{.Values.appName}}-fpm
        - name: {{.Values.appName}}-nginx
          image: nginx:1.15
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: 'Europe/Kiev'
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: nginx-config
