apiVersion: apps/v1
kind: Deployment
metadata:
  name: bills-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bills-be
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: bills-be
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: cm-bills-be-nginx-config
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: bills-be-fpm
          image: ghcr.io/yarsoniy/bills-be-fpm:main
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cm-bills-be-fpm
            - secretRef:
                name: secrets-bills-be-fpm
        - name: bills-be-nginx
          image: nginx:1.15
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: 'Europe/Kiev'
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: nginx-config
